architect:
  - h1alexbel
docker:
  image: l3r8y/rultor-image:1.0.3
assets:
  settings.xml: eo-cqrs/eo-cqrs-secrets#assets/settings.xml
  secring.gpg: eo-cqrs/eo-cqrs-secrets#assets/secring.gpg
  pubring.gpg: eo-cqrs/eo-cqrs-secrets#assets/pubring.gpg
merge:
  script: |-
    mvn clean install -Pqulice-profile -Pqulice --errors --batch-mode
release:
  pre: false
  sensitive:
    - settings.xml
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pqulice-profile -Pqulice -Psonatype --errors --settings ../settings.xml
    mvn clean site-deploy -Pgh-pages -Pqulice-profile -Psite --errors --settings ../settings.xml
